### ISSUE TITLE
Exception - SaveToFile

### ISSUE THREAD

**Issue by jwood36** [Take667/CIS285_EduCal_T1#37]
Unhandled Exception occured when I clicked Save from the MenuStrip.

Steps to Reproduce:

1. Run Application
2. Click "File" menu item
3. Click "Save" sub-menu item

![image](https://github.com/Take667/CIS285_EduCal_T1/assets/53241126/4d60a8b8-82e4-4c2a-84ea-1d925ec06caf)

**Comment by joshSawYou** [comment]
fixed by changing the savefile_click function inside of the frmMain class

**Comment by joshSawYou** [comment]
this is what i changed the function to:
        private void SaveFile_Click(object sender, EventArgs e)
        {
            // Serialize the list of events to JSON
            string json = Newtonsoft.Json.JsonConvert.SerializeObject(events);

            // Specify the file path
            string fileName = "calendar.json";

            // Write the JSON data to the file
            System.IO.File.WriteAllText(fileName, json);

            MessageBox.Show("File saved successfully");
        }
