### ISSUE TITLE
Refactor - List<EventForm>

### ISSUE THREAD

**Issue by jwood36** [Take667/CIS285_EduCal_T1#41]
The Generic DataType `List<EventForm>` is used in multiple locations.  This would be a good candidate for Abstraction into a Class that solely represents this Type Pattern.

I would suggest creating a Short-Hand Class that inherits from `List<EventForm>` and working from that perspective across your code.  Allows for simple coding purposes.

![image](https://github.com/Take667/CIS285_EduCal_T1/assets/53241126/f099d6ad-8f95-456e-8ae7-c503d68dd7de)

**Comment by Take667** [comment]
Added a new class for Events list
