### ISSUE TITLE
frmMain - Event Disorientation

### ISSUE THREAD

**Issue by jwood36** [Take667/CIS285_EduCal_T1#42]
You have several Control Events in the Designer file (`frmMain.Designer.cs`), that should be in the Code file (`frmMain.cs`)

- [x] Move `Exit_Click` from Designer to Code File
- [x] Move `SaveAsFile_Click` from Designer to Code File
- [x] Move `NewEvent_Click` from Designer to Code File
- [x] Move `NewEventForm_Click` from Designer to Code File
- [x] Move `NewSettings_Click` from Designer to Code File
- [x] Move `OpenFile_Click` from Designer to Code File
- [x] Move `NewAboutForm_Click` from Designer to Code File
- [x] Move `SaveFile_Click` from Designer to Code File

**Comment by Take667** [comment]
Moved those features to a separate file.
