### ISSUE TITLE
New Calendar - obscurity

### ISSUE THREAD

**Issue by jwood36** [Take667/CIS285_EduCal_T1#43]
In the Event `NewCalendar_Click` you `BuildNewCalendar` after you `Show`.  This seems counter intuitive, as once you Show the form, everything should already be built.

You can override the `OnShown` event to handle post-visible setup, if you still insist on Building after you Show the form.

From a coding perspective:
* what is the relevance of `BuildNewCalendar` after `Show`?  
* Why must a developer build the new Calendar after the Form is Shown?  
* Should an implementer expect or know to `BuildNewCalendar` after Showing the Form?

**Comment by joshSawYou** [comment]
I have now moved the show to be inside and at the very end of the BuildNewCalendar function. This way, the calendar is built, updated, and lastly shown to show what the new calendar is.
