### ISSUE TITLE
Unused Events - frmAbout

### ISSUE THREAD

**Issue by jwood36** [Take667/CIS285_EduCal_T1#59]
The below events in `frmAbout` have no logic implementation within the body of the method.

- [x] `Form1_Load`
- [x] `editToolStripMenuItem_Click`
- [x] `mnuEditToolStripMenuItem_Click`
- [x] `frmAbout_Load`
- [x] `textBoxDescription_TextChanged`
- [x] `tableLayoutPanel_Paint`

**Comment by Take667** [comment]
I deleted the ToolStripMenuItem
